name: OpenJMU
description: A JMU Flutter application.

version: 0.6.0+95

environment:
    sdk: ">=2.5.0 <3.0.0"
    flutter: ">=1.9.1+hotfix.6"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    badges: 1.1.0
    cached_network_image: 1.1.2+1
    connectivity: 0.4.5+2
    cookie_jar: 1.0.1
    crypto: 2.1.3
    device_info: 0.4.1+1
    dio: 2.1.16
    dragablegridview_flutter: 0.2.5
    event_bus: 1.1.0
    extended_image: 0.6.5
    extended_tabs: 0.2.2
    extended_text: 0.6.6
    extended_text_field: 0.4.4
    fluttertoast: 3.1.3
    flutter_cache_manager: 1.1.2
    flutter_downloader: 1.2.2
    flutter_icons: 0.3.1
    flutter_inappbrowser:
        git: https://github.com/AlexVincent525/flutter_inappbrowser.git
    flutter_native_image:
        git: https://github.com/btastic/flutter_native_image.git
    flutter_platform_widgets: 0.20.2
    flutter_qr_reader: 1.0.3
    flutter_screenutil: 0.6.0
    flutter_svg: 0.14.3
    flutter_webview_plugin: 0.3.8
    html: 0.14.0+3
    image: 2.1.7
    image_crop: 0.3.1
    image_downloader: 0.19.1
    image_gallery_saver: 1.2.2
    image_picker: 0.6.1+10
    intl: any
    like_button: 0.1.9
    multi_image_picker: 4.5.9
    oktoast: 2.2.0
    package_info: 0.4.0+10
    permission_handler: 3.3.0
    pull_to_refresh_notification: 0.3.3
    qr_flutter: 3.0.1
    quick_actions: 0.3.2+2
    shared_preferences: 0.5.4+3
    url_launcher: 5.2.5
    uuid: 2.0.2
    webview_flutter: 0.3.15+1

dev_dependencies:
    flutter_test:
        sdk: flutter


flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/emotionIcons/
        - assets/icons/
        - assets/icons/appCenter/
        - assets/icons/bottomNavigation/
        - assets/icons/gender/
        - assets/icons/postActions/
        - images/
    fonts:
        - family: chocolate
          fonts:
              - asset: assets/fonts/chocolate.ttf
